import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// server component
export const metadata: Metadata = {
  title: "도서 정보",
  description: "Generated by create next app",
};

export default function BookLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return <div>
        {children}
    <h1>HELLO~</h1>
    </div>;
}
